
services:
  bot:
    build:
      context: ./
      platforms:
        - windows/amd64
        - windows/amd64
        - linux/amd64
        - linux/arm64/v8  

    image: showierdata9978/revower
    volumes:
      - ./.env:/.env:mount
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    restart: always
    volumes:
      - type: bind
        source: ./db/
        target: /data/db
